![logo](../../img/license_header_logo.png)
> **Copyright &copy; 2021 CertifAI Sdn. Bhd.**<br>
 <br>
This program is part of OSRFramework. You can redistribute it and/or modify
<br>it under the terms of the GNU Affero General Public License as published by
<br>the Free Software Foundation, either version 3 of the License, or
<br>(at your option) any later version.
<br>
<br>This program is distributed in the hope that it will be useful,
<br>but WITHOUT ANY WARRANTY; without even the implied warranty of
<br>MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
<br>GNU Affero General Public License for more details.
<br>
<br>You should have received a copy of the GNU Affero General Public License
<br>along with this program.  If not, see <http://www.gnu.org/licenses/>.

# 03 - Basic Operations
Authored by: [Kian Yang Lee](https://github.com/KianYang-Lee) - kianyang.lee@certifai.ai

## <a name="description">Notebook Description</a>

Arithmetic is an important building block of numerical computational module. `numpy` supports a wide variety of mathematical operations, which some of the essential ones will be covered in this notebook.

By the end of this tutorial, you will be able to:

1. Apply basic arithmetics on `ndarray`
2. Apply dot product/matrix multiplication on `ndarray`
3. Apply universal functions on `ndarray`

## Notebook Outline
Below is the outline for this tutorial:
1. [Notebook Description](#description)
2. [Notebook Configurations](#configuration)
3. [Basic Arithmetics between `ndarray`](#arithmetics)
4. [Operations between Scalar and `ndarray`](#scalar)
5. [Matrix Multiplication](#mmul)
6. [Universal Functions](#ufunc)
7. [Summary](#summary)
8. [Reference](#reference)

## <a name="configuration">Notebook Configurations</a>
This notebook will works only on `numpy` module, a popular `python` library for numerical computation. It is common for people to import it using the alias `np`.

In [1]:
### BEGIN SOLUTION
import numpy as np
### END SOLUTION

## <a name="arithmetics">Basic Arithmetics between `ndarray`</a>
Let's initialize two arrays for the arithmetic operations.

In [2]:
### BEGIN SOLUTION
arr_1 = np.array([[10, 20, 30, 40, 50, 100]], dtype="float")
arr_2 = np.ones((1, 6))

print("Array 1 is: \n")
print(arr_1)
print("\nArray 2 is: \n")
print(arr_2)
### END SOLUTION

Array 1 is: 

[[ 10.  20.  30.  40.  50. 100.]]

Array 2 is: 

[[1. 1. 1. 1. 1. 1.]]


We can perform arithmetics on `numpy ndarray` using arithmetic operators. The arithmetic operation will be applied elementwise. The operation will return a new `ndarray` with the relevant result by default. You can choose either just specifying the operators or using the methods provided by `numpy` to perform the operations, both return the same result.

In [3]:
# elementwise subtraction
### BEGIN SOLUTION
arr_1 - arr_2 # using subtract operator
np.subtract(arr_1, arr_2) # using numpy method
### END SOLUTION

# assert for array equality
### BEGIN SOLUTION
print("Both methods of performing operation return identical result: ")
print(np.array_equal(arr_1 - arr_2, np.subtract(arr_1, arr_2)))
print("The result is: ")
print(arr_1 - arr_2)
### END SOLUTION

Both methods of performing operation return identical result: 
True
The result is: 
[[ 9. 19. 29. 39. 49. 99.]]


In [4]:
# elementwise addition (either way works)
### BEGIN SOLUTION
arr_1 + arr_2
np.add(arr_1, arr_2)
### END SOLUTION

array([[ 11.,  21.,  31.,  41.,  51., 101.]])

In [5]:
# elementwise multiplication (either way works)
### BEGIN SOLUTION
arr_1 * arr_2
np.multiply(arr_1, arr_2)
### END SOLUTION

array([[ 10.,  20.,  30.,  40.,  50., 100.]])

In [6]:
# elementwise division (either way works)
### BEGIN SOLUTION
arr_2 / arr_1
np.divide(arr_2, arr_1)
### END SOLUTION

array([[0.1       , 0.05      , 0.03333333, 0.025     , 0.02      ,
        0.01      ]])

## <a name="scalar">Operations between Scalar and `ndarray`</a>
`numpy` does not limit its operations between objects of `ndarray` only. It can also be applied to scalar values. The way this works is that `numpy` will broadcast scalar values to the same size of the other `ndarray`. Example of this would be:

In [7]:
# elementwise addition by broadcasting
### BEGIN SOLUTION
arr_1 + 0.1
### END SOLUTION

array([[ 10.1,  20.1,  30.1,  40.1,  50.1, 100.1]])

In [8]:
# elementwise subtraction by broadcasting
### BEGIN SOLUTION
arr_1 - 0.1
### END SOLUTION

array([[ 9.9, 19.9, 29.9, 39.9, 49.9, 99.9]])

In [9]:
# elementwise multiplication by broadcasting
### BEGIN SOLUTION
arr_1 * 0.1
### END SOLUTION

array([[ 1.,  2.,  3.,  4.,  5., 10.]])

In [10]:
# elementwise division by broadcasting
### BEGIN SOLUTION
arr_1 / 0.1
### END SOLUTION

array([[ 100.,  200.,  300.,  400.,  500., 1000.]])

It can even works even when the other object is not a scalar value. When the two `ndarray` are of different sizes, the smaller one will be broadcasted in order to meet the size of the bigger `ndarray` before the operation is performed.

In [11]:
### BEGIN SOLUTION
big_arr = np.array([[2, 4, 6], [8, 10, 12]])
small_arr = np.array([[0.1], [1]])
big_arr + small_arr
### END SOLUTION

array([[ 2.1,  4.1,  6.1],
       [ 9. , 11. , 13. ]])

Take note that certain restrictions need to be met for broadcasting to happen. For example, the operation below will not work.

In [12]:
### BEGIN SOLUTION
np.array([0.1, 1])
### END SOLUTION

array([0.1, 1. ])

In [13]:
try:
    ### BEGIN SOLUTION
    big_arr + np.array([0.1, 1])
    ### END SOLUTION
except ValueError as error:
    print(error)

operands could not be broadcast together with shapes (2,3) (2,) 


## <a name="mmul">Matrix Multiplication</a>
Do note the difference between `*` that performs a elementwise multiplication and `@` that performs a dot product operation. Take a look at the difference between the two operations in the example below.

In [14]:
### BEGIN SOLUTION
arr_3 = np.array([[2,4],[6,8]])
identity_arr = np.identity(2)
print("arr_3 has the ndarray of: ")
print(arr_3)
print("\n\nidentity_arr has the ndarray of below, which is a 2 by 2 identity matrix: ")
print(identity_arr)
### END SOLUTION

arr_3 has the ndarray of: 
[[2 4]
 [6 8]]


identity_arr has the ndarray of below, which is a 2 by 2 identity matrix: 
[[1. 0.]
 [0. 1.]]


In [15]:
print("The dot product of a matrix with identity matrix of the same size should return the identical matrix: ")
### BEGIN SOLUTION
arr_3 @ identity_arr
### END SOLUTION

The dot product of a matrix with identity matrix of the same size should return the identical matrix: 


array([[2., 4.],
       [6., 8.]])

In [16]:
print("The elementwise multiplication of a matrix with identity matrix of the same size returns something else: ")
### BEGIN SOLUTION
arr_3 * identity_arr
### END SOLUTION

The elementwise multiplication of a matrix with identity matrix of the same size returns something else: 


array([[2., 0.],
       [0., 8.]])

Another method to perform dot product is by using `numpy.dot` method, as shown below:

In [17]:
### BEGIN SOLUTION
np.dot(arr_3, identity_arr)
### END SOLUTION

array([[2., 4.],
       [6., 8.]])

Of course, one thing to note is that matrix multiplication is not commutative, thus the order matters! For example:

In [18]:
### BEGIN SOLUTION
arr_4 = np.array([[1,3],[5,7]])
### END SOLUTION

try:
    ### BEGIN SOLUTION
    assert np.array_equal(np.dot(arr_3, arr_4), np.dot(arr_4, arr_3)), "Returned arrays from both operations are different!"
    ### END SOLUTION
except AssertionError as msg:
    print(msg)

Returned arrays from both operations are different!


In [19]:
# dot product of arr_4 and arr_3
### BEGIN SOLUTION
np.dot(arr_4, arr_3)
### END SOLUTION

array([[20, 28],
       [52, 76]])

In [20]:
# dot product of arr_3 and arr_4
### BEGIN SOLUTION
np.dot(arr_3, arr_4)
### END SOLUTION

array([[22, 34],
       [46, 74]])

## <a name="ufunc">Universal Functions</a>
Other general mathematical functions with the likes of sin, cos and exp are available in `numpy` under the names of universal functions (`ufunc`). They operate elementwise on arrays and return a new array result of the operation.

In [21]:
### BEGIN SOLUTION
arr_5 = np.arange(5)
### END SOLUTION

In [22]:
### BEGIN SOLUTION
np.exp(arr_5)
### END SOLUTION

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [23]:
### BEGIN SOLUTION
np.sin(arr_5)
### END SOLUTION

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
### BEGIN SOLUTION
np.cos(arr_5)
### END SOLUTION

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

You can take a look at a more comprehensive list of `ufunc` at `numpy`'s [website](https://numpy.org/doc/stable/reference/ufuncs.html).

##  <a name="summary">Summary</a>
To conclude, you should now be able to:
1. Apply basic arithmetics on `ndarray`
2. Apply dot product/matrix multiplication on `ndarray`
3. Apply universal functions on `ndarray`<br><br>
Congratulations, that concludes this lesson.

## <a name="reference">Reference</a>
* [Universal Functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)
* [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)