![logo](../../img/license_header_logo.png)
> **Copyright &copy; 2021 CertifAI Sdn. Bhd.**<br>
 <br>
This program and the accompanying materials are made available under the
terms of the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0). <br>
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License. <br>
<br>**SPDX-License-Identifier: Apache-2.0**

# 06 - Exercise for Array Creation & Basic Operations
Authored by: [Kian Yang Lee](https://github.com/KianYang-Lee) - kianyang.lee@certifai.ai

## <a name="description">Notebook Description</a>

This notebook serves as an exercise for users to hone their mastery of `numpy` module.

By the end of this tutorial, you will be able to:

1. Explain and apply different methods of `ndarray` creation
2. Explain and apply different basic operations on `ndarray`

## Notebook Outline
Below is the outline for this tutorial:
1. [Notebook Description](#description)
2. [Notebook Configurations](#configuration)
3. [Section I: Array Creation](#create)
4. [Section II: Basic Operations](#operation)
5. [Summary](#summary)

## <a name="configuration">Notebook Configurations</a>
**Task 0:** Import `numpy` module as `np` alias.<br><br>
**Expected Result:**<br>
![06-00](../../img/numpy/06-00.png)

In [1]:
### BEGIN SOLUTION
import numpy as np
### END SOLUTION
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

## <a name="create">Section I: Array Creation</a>

**Task I-1**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-I-01](../../img/numpy/06-I-01.png)

In [2]:
### BEGIN SOLUTION
np.arange(25)
### END SOLUTION

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

**Task I-2**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-I-02](../../img/numpy/06-I-02.png)

In [3]:
### BEGIN SOLUTION
np.arange(start=5, stop=25)
### END SOLUTION

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

**Task I-3**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-I-03](../../img/numpy/06-I-03.png)

In [4]:
### BEGIN SOLUTION
np.arange(start=7, stop=26, step=3)
### END SOLUTION

array([ 7, 10, 13, 16, 19, 22, 25])

**Task I-4**: Create a `ndarray` object as below using `list` object.<br><br>
**Expected Result:**<br>
![06-I-04](../../img/numpy/06-I-04.png)

In [5]:
### BEGIN SOLUTION
np.array([3.5, 2.8, 5.9])
### END SOLUTION

array([3.5, 2.8, 5.9])

**Task I-5**: Create a `ndarray` object as below using `tuple` object.<br><br>
**Expected Result:**<br>
![06-I-05](../../img/numpy/06-I-05.png)

In [6]:
### BEGIN SOLUTION
np.array((3.2, 1.6, 8.889))
### END SOLUTION

array([3.2  , 1.6  , 8.889])

**Task I-6**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-I-06](../../img/numpy/06-I-06.png)

In [7]:
### BEGIN SOLUTION
np.array([
    [2.5, 4.6, 7.8],
    [3.2, 1.5, 4.8]
])
### END SOLUTION

array([[2.5, 4.6, 7.8],
       [3.2, 1.5, 4.8]])

**Task I-7**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-I-07](../../img/numpy/06-I-07.png)

In [8]:
### BEGIN SOLUTION
np.zeros((9,9))
### END SOLUTION

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Task I-8**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-I-08](../../img/numpy/06-I-08.png)

In [9]:
### BEGIN SOLUTION
np.ones((8,8))
### END SOLUTION

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**Task I-9**: Create a `ndarray` object using `numpy.empty` method and print out its `shape`, `size` and `dtype`.<br><br>
**Expected Result:**<br>
![06-I-09](../../img/numpy/06-I-09.png)

In [10]:
### BEGIN SOLUTION
arr_empty = np.empty((3,5))
print(f"The shape of array is : {arr_empty.shape}")
print(f"The size of array is : {arr_empty.size}")
print(f"The dtype of array is : {arr_empty.dtype}")
### END SOLUTION

The shape of array is : (3, 5)
The size of array is : 15
The dtype of array is : float64


**Task I-10**: Convert the `dtype` of previous `ndarray` object created in Task I-09 to `int64`. Note that the elements in the `ndarray` might be different depending on your computer memory allocation, just make sure that the `dtype` is `int64`.<br><br>
**Expected Result:**<br>
![06-I-10](../../img/numpy/06-I-10.png)

In [11]:
arr_empty.astype("int64")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

## <a name=operation>Section II: Basic Operations</a>

**Task II-1**: Create two `ndarray` object as below.<br><br>
**Expected Result:**<br>
![06-II-01](../../img/numpy/06-II-01.png)

In [12]:
### BEGIN SOLUTION
arr_a = np.array([11, 22, 30, 40])
arr_b = np.arange(4)
print(f"Arr_a is \n {arr_a}")
print(f"Arr_b is \n {arr_b}")
### END SOLUTION

Arr_a is 
 [11 22 30 40]
Arr_b is 
 [0 1 2 3]


**Task II-2**: Return `ndarray` as shown below by performing elementwise addition for `arr_a` and `arr_b`.<br><br>
**Expected Result:**<br>
![06-II-02](../../img/numpy/06-II-02.png)

In [13]:
### BEGIN SOLUTION
arr_a + arr_b
### END SOLUTION

array([11, 23, 32, 43])

**Task II-3**: Return `ndarray` as shown below by performing elementwise subtraction for `arr_a` and `arr_b`.<br><br>
**Expected Result:**<br>
![06-II-03](../../img/numpy/06-II-03.png)

In [14]:
### BEGIN SOLUTION
arr_a - arr_b
### END SOLUTION

array([11, 21, 28, 37])

**Task II-4**: Return `ndarray` as shown below by performing elementwise multiplication for `arr_a` and `arr_b`.<br><br>
**Expected Result:**<br>
![06-II-04](../../img/numpy/06-II-04.png)

In [15]:
### BEGIN SOLUTION
arr_a * arr_b
### END SOLUTION

array([  0,  22,  60, 120])

**Task II-5**: Return `ndarray` as shown below by performing dividing `arr_b` with `arr_a`.<br><br>
**Expected Result:**<br>
![06-II-05](../../img/numpy/06-II-05.png)

In [16]:
### BEGIN SOLUTION
arr_b / arr_a
### END SOLUTION

array([0.        , 0.04545455, 0.06666667, 0.075     ])

**Task II-6**: Return `ndarray` as shown below by performing elementwise addition for `arr_a` and a `int` object with value `9`.<br><br>
**Expected Result:**<br>
![06-II-06](../../img/numpy/06-II-06.png)

In [17]:
### BEGIN SOLUTION
arr_a + 9
### END SOLUTION

array([20, 31, 39, 49])

**Task II-7**: Perform matrix multiplication (dot product) with the identity matrix of the given `ndarray`.<br><br>
**Expected Result:**<br>
![06-II-07](../../img/numpy/06-II-07.png)

In [18]:
arr_2D = np.array([[9, 99], [8, 88]])
### BEGIN SOLUTION
arr_2D @ np.identity(2)
### END SOLUTION

array([[ 9., 99.],
       [ 8., 88.]])

**Task II-8**: Perform exponentent operation on `arr_2D`.<br><br>
**Expected Result:**<br>
![06-II-08](../../img/numpy/06-II-08.png)

In [19]:
### BEGIN SOLUTION
np.exp(arr_2D)
### END SOLUTION

array([[8.10308393e+03, 9.88903032e+42],
       [2.98095799e+03, 1.65163625e+38]])

**Task II-9**: Perform logarithm transformation on `arr_2D`.<br><br>
**Expected Result:**<br>
![06-II-09](../../img/numpy/06-II-09.png)

In [20]:
### BEGIN SOLUTION
np.log(arr_2D)
### END SOLUTION

array([[2.19722458, 4.59511985],
       [2.07944154, 4.47733681]])

**Task II-10**: Perform `tangent` operation on `arr_2D`.<br><br>
**Expected Result:**<br>
![06-II-10](../../img/numpy/06-II-10.png)

In [21]:
### BEGIN SOLUTION
np.tan(arr_2D)
### END SOLUTION

array([[ -0.45231566, -25.09253498],
       [ -6.79971146,   0.0354205 ]])

##  <a name="summary">Summary</a>
To conclude, you should now be able to:
1. Explain and apply different methods of `ndarray` creation
2. Explain and apply different basic operations on `ndarray`<br><br>
Congratulations for completing this exercise!    