![logo](../../img/license_header_logo.png)
> **Copyright &copy; 2021 CertifAI Sdn. Bhd.**<br>
 <br>
This program and the accompanying materials are made available under the
terms of the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0). <br>
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License. <br>
<br>**SPDX-License-Identifier: Apache-2.0**

# 07 - Exercise for Iterating, Indexing, and Slicing & Manipulating ndarray
Authored by: [Kian Yang Lee](https://github.com/KianYang-Lee) - kianyang.lee@certifai.ai

## <a name="description">Notebook Description</a>

This notebook serves as an exercise for users to hone their mastery of `numpy` module.

By the end of this tutorial, you will be able to:

1. Perform terating, indexing and slicing operation on `ndarray`
2. Manipulate `ndarray`

## Notebook Outline
Below is the outline for this tutorial:
1. [Notebook Description](#description)
2. [Notebook Configurations](#configuration)
3. [Section I: Iterating, Indexing, and Slicing](#iterate)
4. [Section II: Manipulating `ndarray`](#manipulate)
5. [Summary](#summary)

## <a name="configuration">Notebook Configurations</a>
**Task 0:** Import `numpy` module as `np` alias.<br><br>
**Expected Result:**<br>
![06-00](../../img/numpy/06-00.png)

In [1]:
### BEGIN SOLUTION
import numpy as np
### END SOLUTION
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

## <a name="iterate">Section I: Iterating, Indexing and Slicing</a>

**Task I-1**: Create a `ndarray` object as below.<br><br>
**Expected Result:**<br>
![07-I-01](../../img/numpy/07-I-01.png)

In [2]:
### BEGIN SOLUTION
arr_1 = np.arange(10)
arr_1
### END SOLUTION

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Task I-2**: Write a `for` loop to iterate over each element in the `arr_1` and print them out.<br><br>
**Expected Result:**<br>
![07-I-02](../../img/numpy/07-I-02.png)

In [3]:
### BEGIN SOLUTION
for element in arr_1:
    print(element)
### END SOLUTION

0
1
2
3
4
5
6
7
8
9


**Task I-3**: Write a `for` loop to iterate over each element in the provided `arr_2` and print them out.<br><br>
**Expected Result:**<br>
![07-I-03](../../img/numpy/07-I-03.png)

In [4]:
arr_2 = np.arange(20).reshape(4,5)
### BEGIN SOLUTION
for element in arr_2:
    print(element)
### END SOLUTION

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


**Task I-4**: Using indexing, extract the third element in `arr_1` (note that counting starts from 0).<br><br>
**Expected Result:**<br>
![07-I-04](../../img/numpy/07-I-04.png)

In [5]:
### BEGIN SOLUTION
arr_1[2]
### END SOLUTION

2

**Task I-5**: Using indexing, extract the element in the third row and second column in `arr_2` (note that counting starts from 0).<br><br>
**Expected Result:**<br>
![07-I-05](../../img/numpy/07-I-05.png)

In [6]:
### BEGIN SOLUTION
arr_2[2, 1]
### END SOLUTION

11

**Task I-6**: Using slicing operation, return a slice containing the third element up until last element (inclusive) in `arr_1` (note that counting starts from 0).<br><br>
**Expected Result:**<br>
![07-I-06](../../img/numpy/07-I-06.png)

In [7]:
### BEGIN SOLUTION
arr_1[2:]
### END SOLUTION

array([2, 3, 4, 5, 6, 7, 8, 9])

**Task I-7**: Using slicing operation, return a slice containing the second element up until second last element (inclusive) in `arr_1` (note that counting starts from 0).<br><br>
**Expected Result:**<br>
![07-I-07](../../img/numpy/07-I-07.png)

In [8]:
### BEGIN SOLUTION
arr_1[1:-1]
### END SOLUTION

array([1, 2, 3, 4, 5, 6, 7, 8])

**Task I-8**: Using slicing operation, return a slice containing the elements that are located in first and second row, and third column until second last column.<br><br>
**Expected Result:**<br>
![07-I-08](../../img/numpy/07-I-08.png)

In [9]:
### BEGIN SOLUTION
arr_2[:2, 2:-1]
### END SOLUTION

array([[2, 3],
       [7, 8]])

**Task I-9**: Make a copy of the entire slice of `arr_2`.<br><br>
**Expected Result:**<br>
![07-I-09](../../img/numpy/07-I-09.png)

In [10]:
arr_copy = np.array(())
### BEGIN SOLUTION
arr_copy = arr_2[:].copy()
### END SOLUTION
try:
    assert not np.may_share_memory(arr_copy, arr_2), print("arr_copy is not a new copy!")
    print("arr_copy is not a view of the original array.")
except AssertionError as error:
    error

arr_copy is not a view of the original array.


## <a name="manipulate">Section II: Manipulating `ndarray`</a>

**Task II-1**: Flatten the `arr_3` into 1D array.<br><br>
**Expected Result:**<br>
![07-II-01](../../img/numpy/07-II-01.png)

In [11]:
arr_3 = np.ones((4,3))
### BEGIN SOLUTION
arr_3.ravel()
### END SOLUTION

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Task II-2**: Reshape the `arr_3` into `ndarray` with shape `(3, 4)`.<br><br>
**Expected Result:**<br>
![07-II-02](../../img/numpy/07-II-02.png)

In [12]:
### BEGIN SOLUTION
arr_3.reshape(3, 4)
### END SOLUTION

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Task II-3**: Transpose the provided `arr_4` array.<br><br>
**Expected Result:**<br>
![07-II-03](../../img/numpy/07-II-03.png)

In [13]:
np.random.seed(23)
arr_4 = np.random.rand(2,5)
print("Prior to transpose operation: ")
print(arr_4)
print("Post transpose operation: ")
### BEGIN SOLUTION
arr_4.T
### END SOLUTION

Prior to transpose operation: 
[[0.51729788 0.9469626  0.76545976 0.28239584 0.22104536]
 [0.68622209 0.1671392  0.39244247 0.61805235 0.41193009]]
Post transpose operation: 


array([[0.51729788, 0.68622209],
       [0.9469626 , 0.1671392 ],
       [0.76545976, 0.39244247],
       [0.28239584, 0.61805235],
       [0.22104536, 0.41193009]])

**Task II-4**: Stack provided `arr_5` and `arr_6` vertically (along the first axis).<br><br>
**Expected Result:**<br>
![07-II-04](../../img/numpy/07-II-04.png)

In [14]:
arr_5 = np.ones((3,3))
arr_6 = np.zeros((3,3))
print("Prior to stacking: ")
print("arr_5: ")
print(arr_5)
print("\n\narr_6: ")
print(arr_6)
print("After stacking: ")
### BEGIN SOLUTION
np.vstack((arr_5, arr_6))
### END SOLUTION

Prior to stacking: 
arr_5: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


arr_6: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After stacking: 


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Task II-5**: Stack provided `arr_5` and `arr_6` horizontally (along second axis).<br><br>
**Expected Result:**<br>
![07-II-05](../../img/numpy/07-II-05.png)

In [15]:
print("Prior to stacking: ")
print("arr_5: ")
print(arr_5)
print("\n\narr_6: ")
print(arr_6)
print("After stacking: ")
### BEGIN SOLUTION
np.hstack((arr_5, arr_6))
### END SOLUTION

Prior to stacking: 
arr_5: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


arr_6: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After stacking: 


array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

**Task II-6**: Split the provided `arr_7` horizontally (along the second axis) into two `ndarray`s.<br><br>
**Expected Result:**<br>
![07-II-06](../../img/numpy/07-II-06.png)

In [16]:
arr_7 = np.arange(64).reshape(8,8)
print("Prior to splitting: ")
print(arr_7)
print("After splitting: ")
### BEGIN SOLUTION
np.hsplit(arr_7, 2)
### END SOLUTION

Prior to splitting: 
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
After splitting: 


[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35],
        [40, 41, 42, 43],
        [48, 49, 50, 51],
        [56, 57, 58, 59]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39],
        [44, 45, 46, 47],
        [52, 53, 54, 55],
        [60, 61, 62, 63]])]

**Task II-7**: Split the provided `arr_7` vertically (along the first axis) into two `ndarray`s after second row and fourth row.<br><br>
**Expected Result:**<br>
![07-II-07](../../img/numpy/07-II-07.png)

In [17]:
print("Prior to splitting: ")
print(arr_7)
print("After splitting: ")
### BEGIN SOLUTION
np.vsplit(arr_7, (2, 4))
### END SOLUTION

Prior to splitting: 
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
After splitting: 


[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])]

##  <a name="summary">Summary</a>
To conclude, you should now be able to:
1. Perform terating, indexing and slicing operation on `ndarray`
2. Manipulate `ndarray`<br><br>
Congratulations for completing this exercise!    