![logo](../img/license_header_logo.png)
> **Copyright &copy; 2021 CertifAI Sdn. Bhd.**<br>
 <br>
This program and the accompanying materials are made available under the
terms of the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0). <br>
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License. <br>
<br>**SPDX-License-Identifier: Apache-2.0**

# 01 - Numpy Arrays
Authored by: [Kian Yang Lee](https://github.com/KianYang-Lee) - kianyang.lee@certifai.ai

## <a name="description">Notebook Description</a>

This notebook will works only on `numpy` module, a popular `python` library for numerical computation. This notebook serves as an introduction to the most important data object in the module, which is `numpy array`. 

By the end of this tutorial, you will be able to:

1. Explain about `numpy ndarray` object
2. Apply `numpy.arange()` method to create simple `ndarray`
3. Apply `numpy.ndim`, `numpy.size`, `numpy.shape` and `numpy.dtype` attributes to access these attributes of the relevant `ndarray` object

## Notebook Outline
Below is the outline for this tutorial:
1. [Notebook Description](#description)
2. [Notebook Configurations](#configuration)
3. [Introduction to `numpy ndarray`](#intro)
4. [Attributes of `ndarray`](#attributes)<br>
5. [Another Example](#eg)<br>
6. [n-dimensional Array](#n-dims)
7. [Reference](#reference)

## <a name="configuration">Notebook Configurations</a>
This notebook will works only on `numpy` module, a popular `python` library for numerical computation. It is common for people to import it using the alias `np`.

In [1]:
import numpy as np

## <a name="intro">Introduction to `numpy ndarray`</a>
The main object that the `numpy` module revolves around is the homogeneous, multidimensional array. It is also known as `numpy ndarray` as it can handles and store n-dimensional arrays. An example of `numpy array` looks like this:
<div align="center"> $[[ 0., 1., 2.],$ </div>
<div align="center"> $[ 3., 4., 5.]]$<br>

It is evident that an `ndarray` is a table of elements (you can imagine them as a spreadsheet). One caveat is that all of them are of the same data type (it is float in the example). They are indexed by a tuple of non-negative integers, which corresponds to the respective dimension. Another name for dimensions in `numpy` are axes.

In the example above, the array has 2 axes. The first axis (rows) has a length of 2 because there are two elements (rows) in that dimension. On the other hadn, the second axis (columns) has a length of 3 because there are three elements (columns) in that dimension.
    
We can easily create an `numpy ndarray` with just one line of code. Let's do that and recreate the example we have above.

In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

`np.arange()` returns evenly spaced within the provided interval. In the above example, only the `stop` value is indicated and the default starts from 0, hence the values in the `ndarray` are from 0 to 5 (`stop` value is exclusive).

Based on the printed result, can you guess what is the dimension and shape of the `ndarray`?

## <a name="attributes">Attributes of `ndarray`</a>

Perhaps it is time to talk about the different attributes for `ndarray` object. Here is a non-exhaustive list of commonly used ones:
* `ndarray.ndim`: returns the number of axes (or dimension) of the array.
* `ndarray.shape`: returns a tuple of integers where each integer represents the size (total number of elements) in each dimension.
* `ndarray.size`: returns the total number of elements of the array
* `ndarray.dtype`: returns an object that indicates what are the types of elements in the array.

Before we make use of and call each `ndarray`'s attribute, can you roughly guess what each attribute will return?

In [3]:
arr1 = np.arange(6)

print(f"For the array {arr1}:\n\n") 
print("The number of dimensions is: "+str(arr1.ndim))
print("The shape is: "+str(arr1.shape))
print("The size is: "+str(arr1.size))
print("The data type is: "+str(arr1.dtype))

For the array [0 1 2 3 4 5]:


The number of dimensions is: 1
The shape is: (6,)
The size is: 6
The data type is: int32


Are you able to answer correctly? The `ndarray` is of only one axis, that is why it has the shape `(6,)`. This is also known as one-dimensional vector. It is advisable to convert this into a 2-dimensional matrix as it would result in weird complications when performing numerical computations with other `ndarray` of different shape.

## <a name="eg">Another Example</a>
Let's take a look on another example, whereby this time we will be checking the attributes for a two-dimensional `ndarray`. Before we inspect the attributes, can you roughly guess what are the number of dimensions, shape, size and data type for this `ndarray` below?

In [4]:
arr2 = np.arange(6).reshape(2, 3)

print(f"For the array \n {arr2}\n\n") 
print("The number of dimensions is: "+str(arr2.ndim))
print("The shape is: "+str(arr2.shape))
print("The size is: "+str(arr2.size))
print("The data type is: "+str(arr2.dtype))

For the array 
 [[0 1 2]
 [3 4 5]]


The number of dimensions is: 2
The shape is: (2, 3)
The size is: 6
The data type is: int32


A few things that we can observe here. First, the data type is still `int32`. Next, since the same `np.arange()` method and arguments are used, it result in the same number of elements that are created. 

However, the difference lies in the number of dimension and shape, where it is now of the shape `(2,3)`, where `2` represents the number of elements (rows) in the first axis and `3` represents the number of elements (columns) in the second axis. It has a total of 2 dimensions, so the `ndim` attribute returns 2.

## <a name="n-dims">n-dimensional Array</a>
The strength of `numpy` lies in the ability of handling and storing n-dimensional array in an efficient manner. It is computationally more efficient compared to the native `Python array`. This characteristic enables it to become the module-of-choice when it comes to data analytics and processing using `Python`, as often data analytics requires the user to look through and manipulate a large table of elements with many dimensions. In fact, a lot of the other modules such as `scikit-learn`, `pytorch` and `tensorflow` leverages upon `numpy ndarray` in their module.

Let's create a 4-dimensional `ndarray` as one last check before we ends this tutorial.

In [5]:
arr3 = np.arange(24).reshape(1, 2, 3, 4)

print(f"For the array \n {arr3}\n\n") 
print("The number of dimensions is: "+str(arr3.ndim))
print("The shape is: "+str(arr3.shape))
print("The size is: "+str(arr3.size))
print("The data type is: "+str(arr3.dtype))

For the array 
 [[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


The number of dimensions is: 4
The shape is: (1, 2, 3, 4)
The size is: 24
The data type is: int32


## <a name="reference">Reference</a>
* [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)