![logo](../img/license_header_logo.png)
> **Copyright &copy; 2021 CertifAI Sdn. Bhd.**<br>
 <br>
This program and the accompanying materials are made available under the
terms of the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0). <br>
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License. <br>
<br>**SPDX-License-Identifier: Apache-2.0**

# 03 - Basic Arithmetics
Authored by: [Kian Yang Lee](https://github.com/KianYang-Lee) - kianyang.lee@certifai.ai

## <a name="description">Notebook Description</a>

Arithmetic is an important building block of numerical computational module. `numpy` supports a wide variety of mathematical operations, which some of the essential ones will be covered in this notebook.

By the end of this tutorial, you will be able to:

1. 

## Notebook Outline
Below is the outline for this tutorial:
1. [Notebook Description](#description)
2. [Notebook Configurations](#configuration)
3. [Method 1: Create a Range of Evenly Spaced Values](#arange)
3. [Method 2: Create from `list` or `tuple`](#array)
4. [Method 3: Zeros, Ones and Empty](#similar)
5. [`ndarray` Data-type](#dtype)

## <a name="configuration">Notebook Configurations</a>
This notebook will works only on `numpy` module, a popular `python` library for numerical computation. It is common for people to import it using the alias `np`.

In [2]:
import numpy as np

We can perform arithmetics on `numpy ndarray` using arithmetic operators. The arithmetic operation will be applied elementwise. The operation will return a new `ndarray` with the relevant result by default.

## <a name="arithmetics">Basic Arithmetics</a>
Let's initialize two arrays for the arithmetic operations.

In [6]:
arr_1 = np.array([[10, 20, 30, 40, 50, 100]], dtype="float")
arr_2 = np.ones((1, 6))

print("Array 1 is: \n")
print(arr_1)
print("\nArray 2 is: \n")
print(arr_2)

Array 1 is: 

[[ 10.  20.  30.  40.  50. 100.]]

Array 2 is: 

[[1. 1. 1. 1. 1. 1.]]


We can perform arithmetics on `numpy ndarray` using arithmetic operators. The arithmetic operation will be applied elementwise. The operation will return a new `ndarray` with the relevant result by default. You can choose either just specifying the operators or using the methods provided by `numpy` to perform the operations, both return the same result.

In [18]:
# elementwise subtraction
arr_1 - arr_2 # using subtract operator
np.subtract(arr_1, arr_2) # using numpy method

# assert for array equality
print("Both methods of performing operation return identical result: ")
print(np.array_equal(arr_1 - arr_2, np.subtract(arr_1, arr_2)))
print("The result is: ")
print(arr_1 - arr_2)

Both methods of performing operation return identical result: 
True
The result is: 
[[ 9. 19. 29. 39. 49. 99.]]


In [13]:
np.subtract(arr_1, arr_2)

array([[ 9., 19., 29., 39., 49., 99.]])

In [8]:
# elementwise addition
arr_1 + arr_2

array([[ 11.,  21.,  31.,  41.,  51., 101.]])

In [9]:
# elementwise multiplication
arr_1 * arr_2

array([[ 10.,  20.,  30.,  40.,  50., 100.]])

In [10]:
# elementwise division
arr_2 / arr_1

array([[0.1       , 0.05      , 0.03333333, 0.025     , 0.02      ,
        0.01      ]])